### ISSUE TITLE
gopls "range snippet" translate issue

### ISSUE THREAD

**Issue by jidibinlin** [fejfighter/eglot-tempel#12]
Recently I use eglot-tempel with gopls and I noticed the "range snippet" work in a wrong way.

expected way:

![image](https://github.com/user-attachments/assets/b43e54fe-63f2-4a5e-8c69-c7fbceb0e1a1)

but:
![image](https://github.com/user-attachments/assets/68e4a414-4c9d-444d-b710-032bfa922006)

gopls returned snippet:

"for ${1:}, ${2:} := range rows {\012\011$0\012}"

**Comment by fejfighter** [comment]
Oh.
For my confirmation has it dropped the closing brace?

**Comment by jidibinlin** [comment]
Yes!

**Comment by fejfighter** [comment]
Should work now #13 is in, once melpa picks it up it will be version 0.8.2

**Comment by jidibinlin** [comment]
It works. Thank you!
